use socialnet;
DROP PROCEDURE IF EXISTS Create_user_Or_grant_roles;
drop procedure if exists saveLog;
drop procedure if exists saveLog2;
drop procedure if exists insertUsersIntoDbLoggerIfNotExists;
drop procedure if exists saveProfileLog;
drop procedure if exists limitUseOfCudOperationsOnAccountTypeTable;
drop procedure if exists limitUseOfCudOperationsOnImageTypeTable;
drop procedure if exists limitUseOfCudOperations;
drop procedure if exists insertUsersIntoLoggers;